name: Test

on: [push, pull_request]

jobs:
  unit_tests:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - go-version: 1.17.x
            os: ubuntu-latest
          - go-version: 1.18.x
            os: ubuntu-latest
          - go-version: 1.19.x
            os: ubuntu-latest 
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Make all
        run: make all
      
      - name: Make Test
        run: make test
